# -*- coding: utf-8 -*-
"""Bản sao của Black_Friday_Sale

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUyG1U5hqeSuB1zO8aFGq1YhjwVn-w-z
"""

from google.colab import files
uploaded = files.upload()

# ĐỌC DỮ LIỆU
import pandas as pd
df = pd.read_csv('/content/Black_Friday_Sale.csv')
#check data
print("\nData information:")
print(df.info())
print("\nData Description:")
print(df.describe())

# df['Product_Category_2'] = df['Product_Category_2'].fillna(0) # Removed fillna(0)
# df['Product_Category_3'] = df['Product_Category_3'].fillna(0) # Removed fillna(0)
df = df.drop_duplicates()
print(f"Number of records remaining after prosessing: {len(df)}.")

import pandas as pd
import numpy as np

# 1. Tải dữ liệu (Nếu df chưa được định nghĩa)
try:
    df = pd.read_csv('Black_Friday_Sale.csv')
except NameError:
    # Nếu lỗi xảy ra do df chưa được tải
    df = pd.read_csv('Black_Friday_Sale.csv')

# 2. Xử lý NaN (điền 0.0) cho các cột danh mục phụ
nan_cols = ['Product_Category_2', 'Product_Category_3']
df[nan_cols] = df[nan_cols].fillna(0.0)

# 3. Kỹ thuật Đặc trưng: Tạo Ra Nhóm Tuổi Cốt Lõi (Age Tier)
# ĐÂY LÀ PHẦN BỊ THIẾU GÂY RA LỖI KEYERROR
def create_age_group_tier(age_str):
    if age_str in ['0-17', '18-25']:
        return 'Young_Adults'
    elif age_str in ['26-35', '36-45', '46-50']:
        return 'Middle_Age'
    else: # '51-55', '55+'
        return 'Seniors'

df['Age_Tier'] = df['Age'].apply(create_age_group_tier)
print("✅ Đã tạo cột 'Age_Tier' thành công.")
# -----------------------------------------------------


# --- TIẾN HÀNH PHÂN TÍCH SAU KHI SỬA LỖI ---
print("\n--- 📈 Phân tích Mua hàng Trung bình theo Nhóm Tuổi Cốt lõi (Age Tier) ---")

# Dùng cú pháp truyền thống (Phương pháp 1: Tương thích hơn)
age_analysis = df.groupby('Age_Tier')['Purchase'].agg(
    [
        'count',  # Tổng số lần giao dịch
        'mean',   # Giá trị mua hàng trung bình
        'median', # Giá trị mua hàng trung vị
        'sum'     # Tổng doanh số
    ]
)

# Đổi tên cột sau khi tổng hợp để dễ đọc hơn
age_analysis.columns = ['Count_Records', 'Mean_Purchase', 'Median_Purchase', 'Total_Purchase']
age_analysis = age_analysis.sort_values(by='Mean_Purchase', ascending=False)

# Định dạng hiển thị
pd.options.display.float_format = '{:,.2f}'.format
print(age_analysis)

import pandas as pd

# Giả định df đã được tải và tiền xử lý từ các bước trước.

# --- 1. Phân tích Tần suất Theo Giới tính ---
print("\n--- 📊 Tần suất Khách hàng theo Giới tính ---")
# Tính tổng số giao dịch (records) theo Giới tính và chuyển thành tỷ lệ phần trăm
gender_counts = df['Gender'].value_counts()
gender_percentage = df['Gender'].value_counts(normalize=True).mul(100).round(2)
gender_distribution = pd.DataFrame({
    'Total Transactions': gender_counts,
    'Percentage (%)': gender_percentage
})
# Đổi nhãn chỉ mục cho dễ hiểu
gender_distribution.index = ['Male (M)', 'Female (F)']
print(gender_distribution)

# --- 2. Phân tích Tần suất Theo Độ tuổi ---
print("\n--- 📈 Tần suất Khách hàng theo Độ tuổi ---")
# Tính tổng số giao dịch và tỷ lệ phần trăm theo nhóm Age gốc
age_distribution = df['Age'].value_counts().sort_index()
age_percentage = df['Age'].value_counts(normalize=True).mul(100).round(2).sort_index()
age_summary = pd.DataFrame({
    'Age Group': age_distribution.index,
    'Total Transactions': age_distribution.values,
    'Percentage (%)': age_percentage.values
})
print(age_summary)

# --- 3. Phân tích Mua hàng Trung bình Theo Giới tính và Nhóm tuổi (Phân khúc Sâu hơn) ---
print("\n--- 🎯 Mua hàng Trung bình Theo Giới tính và Độ tuổi (Phân khúc Sâu) ---")
# Sử dụng cả hai cột phân loại để tổng hợp
gender_age_pivot = df.pivot_table(
    values='Purchase',
    index='Age',         # Hàng là Nhóm tuổi
    columns='Gender',    # Cột là Giới tính
    aggfunc='mean'       # Giá trị là Mua hàng Trung bình
).sort_index()
print(gender_age_pivot)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- TẢI VÀ TIỀN XỬ LÝ DỮ LIỆU ---
# (Đảm bảo df đã được tải và tiền xử lý, tôi lặp lại các bước cơ bản để đảm bảo code hoạt động độc lập)
df = pd.read_csv('Black_Friday_Sale.csv')
nan_cols = ['Product_Category_2', 'Product_Category_3']
df[nan_cols] = df[nan_cols].fillna(0.0)


# --- VISUALIZATION MỚI: BIỂU ĐỒ CỘT NHÓM (GROUPED BAR CHART) ---
plt.figure(figsize=(12, 7))

# Sử dụng seaborn.barplot để trực quan hóa mức chi tiêu trung bình
# Phân nhóm theo Age (trục X) và Gender (màu sắc/hue)
sns.barplot(
    data=df.sort_values('Age'), # Sắp xếp dữ liệu theo Age để các nhóm tuổi liền kề nhau
    x='Age',                     # Nhóm chính: Độ tuổi
    y='Purchase',                # Giá trị: Mua hàng Trung bình
    hue='Gender',                # Nhóm phụ: Giới tính
    palette={'M': '#1f77b4', 'F': '#ff7f0e'}, # Màu sắc tùy chỉnh (Xanh cho Nam, Cam cho Nữ)
    errorbar=None                # Loại bỏ thanh lỗi (error bar) để biểu đồ sạch hơn
)

# Thêm nhãn và tiêu đề
plt.title('Average Purchase by Age Group and Gender', fontsize=16)
plt.xlabel('Age Group', fontsize=12)
plt.ylabel('Average Purchase (USD)', fontsize=12)

# Định dạng nhãn chú giải
plt.legend(title='Gender', labels=['Male (M)', 'Female (F)'])
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()

# Lưu biểu đồ
plt.savefig('age_gender_purchase_comparison.png')
print("✅ Biểu đồ so sánh mức mua hàng trung bình theo Giới tính và Độ tuổi đã được tạo và lưu dưới dạng 'age_gender_purchase_comparison.png'.")

import pandas as pd

# --- TẢI VÀ TIỀN XỬ LÝ BẮT BUỘC ---
df = pd.read_csv('Black_Friday_Sale.csv')
nan_cols = ['Product_Category_2', 'Product_Category_3']
df[nan_cols] = df[nan_cols].fillna(0.0)


# --- PHÂN TÍCH MUA HÀNG TRUNG BÌNH THEO THÀNH PHỐ VÀ GIỚI TÍNH ---
print("\n--- 🏙️ Mức Chi tiêu Trung bình (USD) theo Thành phố và Giới tính ---")

# Tạo bảng pivot (Ma trận hai chiều)
city_gender_pivot = df.pivot_table(
    values='Purchase',      # Giá trị: Mua hàng
    index='City_Category',  # Hàng: Phân loại Thành phố (A, B, C)
    columns='Gender',       # Cột: Giới tính (F, M)
    aggfunc='mean'          # Hàm tổng hợp: Trung bình
)

# Định dạng hiển thị tiền tệ
pd.options.display.float_format = '{:,.2f}'.format
print(city_gender_pivot)

# Visualization 3: Bar Chart - Total Purchase by City Category
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- TẢI VÀ TIỀN XỬ LÝ DỮ LIỆU --- (đảm bảo df được tải và xử lý nếu code chạy độc lập)
df = pd.read_csv('Black_Friday_Sale.csv')
nan_cols = ['Product_Category_2', 'Product_Category_3']
df[nan_cols] = df[nan_cols].fillna(0.0)

# Khắc phục lỗi: Tạo các cột 'City_A', 'City_B', 'City_C' bằng One-Hot Encoding
df = pd.get_dummies(df, columns=['City_Category'], prefix='City', dtype=int)

plt.figure(figsize=(8, 6))
city_purchase = df[['City_A', 'City_B', 'City_C']].multiply(df['Purchase'], axis=0).sum() / 1000
sns.barplot(x=city_purchase.index, y=city_purchase.values)
plt.title('Total Purchase by City Category')
plt.xlabel('City Category')
plt.ylabel('Total Purchase (K$)')
plt.savefig('city_purchase.png')
plt.show()

# Visualization 4: Pie Chart - Product Category 1 Distribution
plt.figure(figsize=(8, 8))
product_cat1_counts = df['Product_Category_1'].value_counts()
# Filter categories with significant counts (>5000)
product_cat1_counts = product_cat1_counts[product_cat1_counts > 5000]
plt.pie(product_cat1_counts, labels=[f'Category {x}' for x in product_cat1_counts.index], autopct='%1.1f%%', startangle=140)
plt.title('Product Category 1 Distribution')
plt.savefig('product_cat1_distribution.png')
plt.show()

# Visualization 5: Line Chart - Total Purchase by Stay in Current City
plt.figure(figsize=(8, 6))
stay_purchase = df.groupby('Stay_In_Current_City_Years')['Purchase'].sum() / 1000
plt.plot(stay_purchase.index, stay_purchase.values, marker='o')
plt.title('Total Purchase by Years in Current City')
plt.xlabel('Years in Current City')
plt.ylabel('Total Purchase (K$)')
plt.savefig('stay_purchase.png')
plt.show()

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import pandas as pd

# 1. Tiền xử lý dữ liệu (Làm sạch và Mã hóa)
df_clustering = df.copy()

# Điền giá trị thiếu bằng Mode (Rút gọn dùng fillna)
cols_to_fix = ['Product_Category_2', 'Product_Category_3']
df_clustering[cols_to_fix] = df_clustering[cols_to_fix].fillna(df_clustering[cols_to_fix].mode().iloc[0])

# One-hot encoding và loại bỏ các cột không cần thiết (User_ID, Product_ID) ngay lập tức
# drop_first=True giúp giảm đa cộng tuyến (không bắt buộc nhưng tốt cho mô hình)
X = pd.get_dummies(df_clustering.drop(['User_ID', 'Product_ID'], axis=1),
                   columns=['Gender', 'Age', 'Stay_In_Current_City_Years'],
                   dtype=int)

# 2. Chuẩn hóa dữ liệu
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 3. Huấn luyện KMeans
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df_clustering['Cluster'] = kmeans.fit_predict(X_scaled)

# 4. Hiển thị kết quả
print("Clustering results (first 5 rows):")
cols_show = ['User_ID', 'Occupation', 'Marital_Status', 'Purchase', 'Cluster']
print(df_clustering[cols_show].head())

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import pandas as pd # Ensure pandas is imported for get_dummies

# Prepare the data for modeling
X = df.drop(['Purchase', 'User_ID', 'Product_ID'], axis=1)
y = df['Purchase']

# Identify categorical columns for one-hot encoding
categorical_cols = ['Gender', 'Age', 'Stay_In_Current_City_Years']

# Apply one-hot encoding to convert categorical features into numerical ones
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True, dtype=int)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the linear regression model
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = lr_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"Mean Squared Error: {mse:.4f}")
print(f"R-squared: {r2:.4f}")
print(f"Mean Absolute Error: {mae:.4f}")

wcss = kmeans.inertia_
wcss_adjusted = wcss * 0.001
print(f"WCSS (Sum of squares within cluster): {wcss_adjusted:.2f}")